### ISSUE TITLE
支持QQ频道使用

### ISSUE THREAD

**Issue by jiangyin14** [ikechan8370/Yunzai-Github-Event#1]
大佬好，在测试中本插件如果在“群号部分”填入QQ频道中的“qg_aaaaaaa-bbbbb”这样的子频道id无法使用（表现为不启动插件 监听端口），恳请您对频道进行适配🙏
感谢大佬

**Comment by ikechan8370** [comment]
应该没有这样的限制。你是怎么填的？是不是没加引号之类的问题

**Comment by jiangyin14** [comment]
感谢大佬回复。
我没加引号 我是傻逼
